accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('send-email/', views.send_email, name='send_email'),
    path('send-email/done/', views.send_email_done, name='send_email_done'),
    path('user-delete/', views.user_delete, name='user_delete'),
    path('signUp/', views.signUp, name='signUp'), #회원가입
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'), #로그인
    path('signUp/id-check/', views.check_id, name='id-check'), #아이디 중복 검사
    path('signUpComplete/', views.signUpComplete, name='signUpComplete'), #회원가입 완료
    path('user-page/', views.user_page, name='user_page'), #마이페이지
    path('logout/', views.logout_view, name='logout'),
    path('<int:settle_id>/settle-is-check/', views.settle_check, name='settle-check'),
    path('account-change/', views.account_change, name='account_change'),
    path('nickname-change/', views.nickname_change, name='nickname_change'),
    path('user-write-board/', views.user_write_board, name='user_write_board'),
    path('user-participate-board/', views.user_participate_board, name='user_participate_board'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.board_main, name='main'),
    path('write/', views.board_write, name='write'),
    path('<int:meeting_id>/', views.board_detail, name='detail'),
    path('<int:meeting_id>/edit/', views.board_edit, name='edit'),
    path('<int:meeting_id>/delete/', views.board_delete, name='delete'),
    path('<int:meeting_id>/comment-delete/<int:comment_id>/', views.comment_delete, name='comment-delete'),
    path('<int:meeting_id>/participate/', views.board_participate, name='participate'),
    path('<int:meeting_id>/participate-delete/', views.board_participate_delete, name='participate-delete'),
    path('<int:meeting_id>/gather-done/', views.board_gather_done, name='gather-done'),
    path('<int:meeting_id>/settle/', views.board_settle, name='settle'),
    path('<int:meeting_id>/meeting-complete/', views.board_meeting_complete, name='meeting-complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', views.index, name='index'), #루트 페이지 설정(고치자..)
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

accounts/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.db import models
from django.contrib.auth.models import AbstractBaseUser


class UserManager(BaseUserManager):
    def create_user(self, user_id, nickname, bank, account_no, password=None):
        if not user_id:
            raise ValueError('아이디는 필수 입력입니다.')

        if not nickname:
            raise ValueError('닉네임은 필수 입력입니다.')

        if not bank:
            raise ValueError('은행명은 필수 입력입니다.')

        if not account_no:
            raise ValueError('계좌번호는 필수 입력입니다.')

        user = self.model(
            user_id=user_id,
            nickname=nickname,
            bank=bank,
            account_no=account_no
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, user_id, nickname, bank, account_no, password=None):
        user = self.create_user(
            user_id=user_id,
            nickname=nickname,
            bank=bank,
            account_no=account_no,
            password=password
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class Member(AbstractBaseUser):
    user_id = models.CharField(primary_key=True,max_length=15, null=False, blank=False, unique=True)
    nickname = models.CharField(null=False, max_length=8, blank=False)
    bank = models.CharField(null=False, max_length=20, blank=False)
    account_no = models.CharField(max_length=20, blank=False)

    # 추가 필드 정의
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'user_id'
    REQUIRED_FIELDS = ['nickname', 'bank', 'account_no']

    def __str__(self):
        return self.user_id

    @property
    def is_staff(self):
        return self.is_admin

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from .models import Member
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import ReadOnlyPasswordHashField


#유저 생성 폼
class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Member
        fields = ['user_id', 'nickname', 'bank', 'account_no']

    # 비밀번호 일치 검사
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("비밀번호가 다릅니다. 다시 확인해주세요.")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


    def clean_account_no(self): #계좌번호 방지 함수
        account_no = self.cleaned_data.get('account_no')

        # 계좌번호 최대 입력 글자
        if len(account_no) > 20:
            raise forms.ValidationError('최대 20자까지 입력 가능합니다.')

        # 계좌번호가 숫자로만 구성되어 있는지 확인
        if not account_no.isdigit():
            raise forms.ValidationError('계좌번호는 숫자로만 입력해주세요.')

        # 계좌번호 중복 검사
        if account_no:
            qs = Member.objects.filter(account_no=account_no)
            if qs.exists():
                raise forms.ValidationError('이미 등록된 계좌입니다. 다시 입력해주세요.')
            return account_no



# 유저 수정 폼
class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = Member
        fields = ['user_id', 'nickname', 'bank', 'account_no']

    def clean_password(self):
        return self.initial["password"]

accounts/views.py
# Create your views here.
from django.http import HttpResponse
from django.http import JsonResponse
from .models import Member
from boards.models import *
from django.shortcuts import render, redirect
from accounts.forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from datetime import timedelta
from django.core.mail import EmailMessage


def index(request): #루트 페이지
    participate_count = 0
    if request.user.is_authenticated:
        # 모임 참여 횟수 구하기(모집 완료된 것만 카운트 + 내가 쓴 글도 카운트)
        meetings = Participation.objects.filter(user=request.user)
        for meeting in meetings:
            meeting_detail = Meeting.objects.get(id=meeting.meeting_id)
            # print(meeting_detail.status.status_number >= 1)
            if meeting_detail.status.status_number >= 1:
                participate_count += 1

        # 모임 개설 횟수 구하기
        open_meeting_list = Meeting.objects.filter(user_id=request.user)
        meeting_open_count = len(open_meeting_list)

        # 정산 내역 가져오기
        now = timezone.now()
        five_days_ago = now - timedelta(days=5) #5일치
        settle_list = SettleUp.objects.filter(user=request.user, created_at__gte=five_days_ago)
        settle_list = settle_list.order_by('-created_at')
        context = {
            'participate_count': participate_count,
            'meeting_open_count': meeting_open_count,
            'settle_list': settle_list,
        }
        return render(request, 'accounts/home.html', context)
    else:
        return render(request, 'accounts/login.html')


# 정산 내역 체크 - DB에 저장
def settle_check(request, settle_id):
    settle = SettleUp.objects.get(id=settle_id)
    if settle.is_check:
        settle.is_check = False
    else:
        settle.is_check = True
    settle.save()
    return redirect('/')


#회원가입
def signUp(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            user_id = form.cleaned_data.get('user_id')
            password = form.cleaned_data.get('password1')
            print(f"user_id: {user_id}, password: {password}")
            user = authenticate(username=user_id, password=password)
            if user is not None:
                # login(request, user)
                return redirect('accounts:signUpComplete')
            else:
                print("Authentication failed")
    else:
        form = SignupForm()
    return render(request, 'accounts/signUp.html', {'form':form})


# 회원 탈퇴
def user_delete(request):
    if request.method == 'POST':
        if 'check' in request.POST:
            print('체크함...')
    return render(request, 'accounts/user_delete.html')


#아이디 중복검사
def check_id(request):
    user_id = request.POST.get('user_id')
    is_taken = Member.objects.filter(user_id=user_id).exists() #아이디값이 존재하는지
    return JsonResponse({'is_taken': is_taken}) #결과 전송(json으로)


# 회원가입 완료 페이지
def signUpComplete(request):
    return render(request, 'accounts/signUpComplete.html')


# 마이페이지
def user_page(request):
    return render(request, 'accounts/myPage.html')


# 로그아웃
def logout_view(request):
    logout(request)
    return redirect('accounts:login')


# 계좌 변경
def account_change(request):
    user = Member.objects.get(user_id=request.user)
    if request.method == 'POST':
        bank = request.POST['bank']
        account_no = request.POST['account_no']

        # 계좌번호 숫자만 입력했는지 검사
        if not account_no.isdigit():
            error = '계좌는 숫자로만 입력해주세요.'
            return render(request, 'accounts/account_change.html', {'user': user, 'error': error})

        # 계좌번호 중복 검사
        if Member.objects.filter(account_no=account_no).exists():
            error = '이미 등록된 계좌입니다. 다시 입력해 주세요.'
            return render(request, 'accounts/account_change.html', {'user': user, 'error': error})

        # 변경
        user.bank = bank
        user.account_no = account_no
        user.save()
        print("성공!")
        return redirect('accounts:account_change')
    context = {
        'user': user,
    }
    return render(request, 'accounts/account_change.html', context)

# 닉네임 변경
def nickname_change(request):
    user = Member.objects.get(user_id=request.user)
    if request.method == 'POST':
        nickname = request.POST['nickname']
        user.nickname = nickname
        user.save()
        return redirect('accounts:nickname_change')
    return render(request, 'accounts/nickname_change.html', {'user': user})


# 내가 쓴 모임 (모임 작성 아이디가 유저 아이디와 같은 것들)
def user_write_board(request):
    meeting_list = Meeting.objects.filter(user_id=request.user).order_by('-created_at')
    return render(request, 'boards/user_write_board.html',
                  {'meeting_list': meeting_list})


# 내가 참여한 모임
def user_participate_board(request):
    meeting_id_list = Participation.objects.filter(user=request.user).values_list('meeting', flat=True) # 모임 객체 가져오기

    # 해당 모임들 중에서 사용자가 생성자가 아닌 모임만 필터링
    meeting_list = Meeting.objects.filter(id__in=meeting_id_list).exclude(user_id=request.user).order_by('-created_at')

    return render(request, 'boards/user_participate_board.html',
                  {'meeting_list': meeting_list})


# 메일 발송
def send_email(request):
    if request.method == 'POST':
        email = request.POST['email']
        email_validation = email[email.find('@') + 1:]

        # 학교 이메일인지 검사
        if email_validation != 'student.hywoman.ac.kr':
            error = '학교 이메일 주소를 입력해 주세요.'
            return render(request, 'accounts/send_email.html', {'error': error})

        url = 'http://localhost:8000/accounts/signUp/'
        email_message = EmailMessage(
            '함께나리 회원가입',  # 이메일 제목
            f'<h2>안녕하세요. 함께나리입니다.</h2><p>회원가입을 완료하려면 아래를 클릭해 주세요!</p><a href="{url}">클릭</a>',  # 이메일 본문
            'johh0588@naver.com',  # 발신자 이메일 주소
            [email],  # 수신자 이메일 리스트
            headers={'Reply-To': '함께나리@naver.com'}  # 별칭 이메일 주소로 회신받고 싶을 때
        )
        email_message.content_subtype = 'html'
        email_message.send()
        return redirect('accounts:send_email_done')

    return render(request, 'accounts/send_email.html')


# 메일 발송 완료
def send_email_done(request):
    return render(request, 'accounts/send_mail_complete.html')

templates/accounts/account_change.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/account_change.css' %}">
            <div class="top-logo">
                <div class="move-back">
                    <a href="{% url 'accounts:user_page' %}">
                        <img src="{% static 'image/back.png' %}" alt="">
                    </a>
                </div>
                계좌 변경
            </div>
            
            <div class="bank-account">
                <img src="{% static 'image/bank-account.png' %}" alt="">
                <div class="notice">※ 기존 정산 내역에는 적용되지 않습니다!</div>
            </div>

            <div class="current-account">현재 계좌</div>
            <div class="bank-read">
                <input type="text" placeholder="{{ user.bank }}" readonly>
                <input type="text" placeholder="{{ user.account_no }}" readonly>
            </div>

            <div class="new-account">변경할 계좌</div>
            <div>
                <form action="{% url 'accounts:account_change' %}" method="post" class="account-form">
                    {% csrf_token %}
                    <input type="text" name="bank" placeholder="은행명" required><br>
                    <input type="text" name="account_no" id="account_no" placeholder="계좌번호(- 빼고)" maxlength="20" required><br>

                    <button type="submit" class="submit-btn">변경하기</button> <!--⭐제출버튼-->
                </form>

                {% if error %}
                    <div class="error">{{ error }}</div>
                {% endif %}
            </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/account_change.js' %}"></script>
{% endblock %}

templates/accounts/home.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
            <img src="{% static 'image/home-img.png' %}" alt="" class="home-img"> <!--홈 화면 이미지-->

            <div class="row" id="group-info"> <!--모임 횟수 관련 부분-->
                <div class="col">
                    <div class="info-name-participate">모임 참여 횟수</div>
                    <div class="participate-count">{{ participate_count }}</div> <!--⭐⭐여기 회원의 모임 참여 횟수-->
                </div>
                <div class="col">
                    <div class="info-name-open">모임 개설 횟수</div>
                    <div class="open-count">{{ meeting_open_count }}</div> <!--⭐⭐여기 회원의 모임 개설 횟수-->
                </div>
            </div>

            <div class="pay"> <!--송금 내역 관리 부분-->
                <div class="pay-title">
                    <img src="{% static 'image/money.svg' %}" alt="">
                    잠깐! 송금하셨나요? <span class="settle-notice">(5일 치 정산 내역이 보여집니다)</span>
                </div>

                <div class="pay-check"> <!--⭐⭐ 여기 송금 내역 관리-->
                    {% if not settle_list %}
                        <div class="no-settle-img">
                            <img src="{% static 'image/no-settle.png' %}" alt="">
                        </div>
                        <div class="no-settle-notice">보낼 정산 내역이 없어요!</div>
                    {% endif %}
                    {% for settle in settle_list %}
                        <a href="{% url 'accounts:settle-check' settle.id %}">
                            <div class="pay-detail">
                                {% if settle.is_check %}
                                    <img src="{% static 'image/check.png' %}" alt="">
                                {% else %}
                                    <img src="{% static 'image/not-check.png' %}" alt="">
                                {% endif %}
                                <div>{{ settle.bank }} {{ settle.account_no }} {{ settle.amount }}원</div>
                            </div>
                        </a>
                    {% endfor %}
                </div>
            </div>
        {% include 'menuBar_home.html' %}

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/home.js' %}"></script>
{% endblock %}

templates/accounts/login.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
        <div class="contents"> <!--전체 컨텐츠 영역-->
            <div class="page-banner"> <!--배너 영역-->
                <div class="banner-title">함께나리,</div>
                <div class="banner-content">
                    재학생들을 모아<br>
                    택시 모임을 이용해보세요!
                </div>
                <div class="banner-img"> <!--배너에 사용되는 이미지-->
                    <img src="{% static 'image/group_taxi.png' %}" alt="">
                </div>
            </div>

            <!-- ⭐⭐여기 로그인 폼 -->
            <form action="{% url 'accounts:login' %}" method="post" class="login-form"> <!--로그인 폼-->
                {% csrf_token %}
                <input type="text" id="user_id" name="username" placeholder="아이디" value="{{ form.username.value|default_if_none:'' }}" required>
                <input type="password" id="password" name="password" placeholder="비밀번호" value="{{ form.password.value|default_if_none:'' }}" required>
                <button type="submit" class="login-btn">로그인</button>
            </form>

            <div class="sign-up">
                회원이 아니신가요?
                <a href="{% url 'accounts:send_email' %}"> <!--⭐⭐여기 링크-->
                    회원가입
                </a>
            </div>
        </div>
{% endblock %}

templates/accounts/myPage.html
{% extends 'base.html' %}
{% block content %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/myPage.css' %}">
            <div class="profile">
                <img src="{% static 'image/profile.png' %}" alt="">
                <div class="nickname">{{ user.nickname }}</div> <!--⭐⭐여기 유저 닉네임-->
            </div>


            <div class="row" id="user-group">
                <a href="{% url 'accounts:user_write_board' %}" class="col"> <!--⭐⭐여기 링크 연결-->
                    <div class="user-write-img">
                        <img src="{% static 'image/user-write-group.png' %}" alt="">
                    </div>
                    <div class="user-write">
                        작성한 모임
                    </div>
                </a>
                <a href="{% url 'accounts:user_participate_board' %}" class="col"> <!--⭐⭐여기 링크 연결-->
                    <div class="user-participate-img">
                        <img src="{% static 'image/user-group-participate.png' %}" alt="">
                    </div>
                    <div class="user-participate">
                        참여한 모임
                    </div>
                </a>
            </div>

            <div class="accoount-setting"> <!--계정 설정 부분-->
                <div class="account-text">계정</div>
                <div class="passwd-change"><a href="{% url 'accounts:account_change' %}">계좌 변경</a></div>
                <div class="nickname-change"><a href="{% url 'accounts:nickname_change' %}">닉네임 변경</a></div>
            </div>

            <div class="other-setting"> <!--계정 설정 부분-->
                <div class="other-text">기타</div>
                <div class="logout"><a href="{% url 'accounts:logout' %}">로그아웃</a></div>
                <div class="user-delete"><a href="{% url 'accounts:user_delete' %}">회원탈퇴</a></div>
            </div>
        {% include 'menuBar_mypage.html' %}
{% endblock %}

templates/accounts/nickname_change.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/nickname_change.css' %}">
            <div class="top-logo">
                <div class="move-back">
                    <a href="{% url 'accounts:user_page' %}">
                        <img src="{% static 'image/back.png' %}" alt="">
                    </a>
                </div>
                닉네임 변경
            </div>
            
            <div class="nickname">
                <img src="{% static 'image/profile.png' %}" alt="">
                <div class="nickname-text">{{ user.nickname }}</div>
            </div>
            
            <div>
                <form action="{% url 'accounts:nickname_change' %}" method="post" class="nickname-change-form">
                    {% csrf_token %}
                    <input type="text" name="nickname" maxlength="8" placeholder="닉네임(8자 이하)" required><br>
                    <button type="submit" class="submit-btn">변경하기</button> <!--⭐제출버튼-->
                </form>
            </div>
{% endblock %}

templates/accounts/send_email.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/send_email.css' %}">
            <div class="page-banner"> <!--배너 부분-->
                <div class="banner-text"> <!--배너 텍스트 부분-->
                    <div class="banner-title"> <!--배너 제목 부분-->
                        회원가입,
                    </div>
                    <div class="banner-content"> <!--배너 내용 부분-->
                        정보를<br> 입력해주세요!
                    </div>
                </div>

                <div class="banner-img"> <!--배너 이미지 부분-->
                    <img src="{% static 'image/sign-up.png' %}" alt=""> <!--⭐⭐여기 사진 링크-->
                </div>
            </div>

            <form action="{% url 'accounts:send_email' %}" method="post" class="signUp-form">
                {% csrf_token %}
                <div class="notice">한양여자대학교 학생 이메일을 입력하여 진행하세요!</div>
                <input type="email" name="email" id="email" placeholder="@student.hywoman.ac.kr" required>

                {% if error %}
                    <div class="error">{{ error }}</div>
                {% endif %}

                <button type="submit" class="submit-btn">발송하기</button> <!--⭐제출버튼-->
            </form>

            <a href="{% url 'accounts:login' %}" class="go-login">돌아가기</a>
{% endblock %}

templates/accounts/send_mail_complete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/send_email_complete.css' %}">
            <div class="top-logo">
                함께나리
            </div>
            
            <div class="mail-img">
                <img src="{% static 'image/send-mail.png' %}" alt="">
            </div>

            <div class="notice">메일을 전송했습니다.</div>
            <div class="notice">메일함을 확인해 주세요!</div>

            <a href="{% url 'accounts:login' %}" class="go-login">확인</a>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
{% endblock %}

templates/accounts/signUp.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/signUp.css' %}">
            <div class="page-banner"> <!--배너 부분-->
                <div class="banner-text"> <!--배너 텍스트 부분-->
                    <div class="banner-title"> <!--배너 제목 부분-->
                        회원가입,
                    </div>
                    <div class="banner-content"> <!--배너 내용 부분-->
                        정보를<br> 입력해주세요!
                    </div>
                </div>

                <div class="banner-img"> <!--배너 이미지 부분-->
                    <img src="{% static 'image/sign-up.png' %}" alt=""> <!--⭐⭐여기 사진 링크-->
                </div>
            </div>

            <form action="{% url 'accounts:signUp' %}" method="post" class="signUp-form"> <!--⭐⭐여기 회원가입 form-->
                {% csrf_token %}
                <div class="form-input">
                    <label for="nickname">닉네임</label> <!--⭐닉네임-->
                    <div class="nickname">
                        <input type="text" id="nickname" name="nickname" placeholder="닉네임(8자 이하)" value="{{ form.nickname.value|default_if_none:'' }}" maxlength="8" required>
                        {% if form.nickname.errors %}
                            <div class="error">{{ form.nickname.errors }}</div>
                        {% endif %}
                    </div>

                    <label for="bank">은행명</label> <!--⭐은행명-->
                    <div class="bank">
                        <input type="text" id="bank" name="bank" placeholder="은행명 ex)국민" value="{{ form.bank.value|default_if_none:'' }}" required>
                        {% if form.bank.errors %}
                            <div class="error">{{ form.bank.errors }}</div>
                        {% endif %}
                    </div>

                    <label for="account_no">계좌번호</label> <!--⭐계좌번호-->
                    <div class="account_no">
                        <input type="text" id="account_no" name="account_no" placeholder="계좌번호(- 빼고)" value="{{ form.account_no.value|default_if_none:'' }}" maxlength="20" required>
                        {% if form.account_no.errors %}
                            {% for error in form.account_no.errors %}
                            <div class="error">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <label for="user_id">아이디</label> <!--⭐아이디-->
                    <div class="id">
                        <input type="text" id="user_id" name="user_id" placeholder="아이디(15자리 이하)" value="{{ form.user_id.value|default_if_none:'' }}" maxlength="15" required>
                        <button type="button" id="idCheckBtn">중복검사</button>
                        <input type="hidden" name="idCheck" value="false" id="idCheckSuccess"> <!--⭐아이디 중복검사 확인값-->
                        <div id="idCheckResponse"></div>
                        {% if form.user_id.errors %}
                            {% for error in form.user_id.errors %}
                            <div class="error">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>

                    <label for="password1">비밀번호</label> <!--⭐비밀번호-->
                    <div class="passwd">
                        <input type="password" id="password1" name="password1" placeholder="비밀번호(8자리 이상~15자리 이하)" value="{{ form.password1.value|default_if_none:'' }}" maxlength="15" required>
                        <button type="button" id="passwd-icon">
                            <img src="{% static 'image/eye-close.png' %}" alt="">
                        </button>
                    </div>

                    <label for="password2">비밀번호 확인</label>
                    <div class="passwd-check">
                        <input type="password" id="password2" name="password2" placeholder="비밀번호 확인" value="{{ form.password2.value|default_if_none:'' }}" maxlength="15" required>
                        {% if form.password2.errors %}
                            {% for error in form.password2.errors %}
                            <div class="error">{{ error }}</div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>

                <button type="submit" class="submit-btn">가입하기</button> <!--⭐제출버튼-->
            </form>

            {% if form.non_field_errors %}
                <div class="error">
                    {{ form.non_field_errors }}
                </div>
            {% endif %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/signUp.js' %}"></script>
{% endblock %}

templates/accounts/signUpComplete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/signUpComplete.css' %}">
            <div class="top-logo">
                함께나리
            </div>

            <img src="{% static 'image/complete.png' %}" alt="">

            <div class="complete-text">
                회원가입 완료!
            </div>

            <div class="text">
                함께나리에 가입이 완료되었습니다.
            </div>

            <a href="{% url 'accounts:login' %}"> <!--⭐⭐여기 링크 연결-->
                <button type="button">
                    확인
                </button>
            </a>
{% endblock %}

templates/accounts/user_delete.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/user_delete.css' %}">
            <div class="top-logo">
                <div class="move-back">
                    <a href="{% url 'accounts:user_page' %}">
                        <img src="{% static 'image/back.png' %}" alt="">
                    </a>
                </div>
                회원탈퇴
            </div>

            <div class="title-text">함께나리를</div>
            <div class="title-text-color">탈퇴하실건가요?</div>

            <div class="notice-guide">잠깐! 탈퇴하시기 전에<br>
                아래 사항을 확인해 주세요!</div>

            <div class="notice-box">
                <ul class="list">
                    <li>기존에 작성한 게시물과 댓글은 삭제되지 않습니다. 다만, 닉네임은 (알 수 없음) 으로 표시됩니다.</li>
                    <li>다른 회원에게 보내진 정산 내역은 확실한 정산을 위해 삭제되지 않습니다.</li>
                    <li>다시 가입하시게 될 시, 처음부터 다시 회원가입을 진행해야합니다.</li>
                </ul>
            </div>

            <form action="{% url 'accounts:user_delete' %}" method="post" class="form">
                {% csrf_token %}
                <div class="form-check">
                    <input class="form-check-input" type="checkbox" id="flexCheckDefault" name="check">
                    <label class="form-check-label" for="flexCheckDefault">
                        유의사항을 모두 확인했습니다.
                    </label>
                    <div class="error"></div>
                </div>

                <button type="submit" class="submit-btn">탈퇴하기</button>
            </form>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/user_delete.js' %}"></script>
{% endblock %}