accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('send-email/', views.send_email, name='send_email'),
    path('send-email/done/', views.send_email_done, name='send_email_done'),
    path('user-delete/', views.user_delete, name='user_delete'),
    path('signUp/', views.signUp, name='signUp'), #회원가입
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'), #로그인
    path('signUp/id-check/', views.check_id, name='id-check'), #아이디 중복 검사
    path('signUpComplete/', views.signUpComplete, name='signUpComplete'), #회원가입 완료
    path('user-page/', views.user_page, name='user_page'), #마이페이지
    path('logout/', views.logout_view, name='logout'),
    path('<int:settle_id>/settle-is-check/', views.settle_check, name='settle-check'),
    path('account-change/', views.account_change, name='account_change'),
    path('nickname-change/', views.nickname_change, name='nickname_change'),
    path('user-write-board/', views.user_write_board, name='user_write_board'),
    path('user-participate-board/', views.user_participate_board, name='user_participate_board'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.board_main, name='main'),
    path('write/', views.board_write, name='write'),
    path('<int:meeting_id>/', views.board_detail, name='detail'),
    path('<int:meeting_id>/edit/', views.board_edit, name='edit'),
    path('<int:meeting_id>/delete/', views.board_delete, name='delete'),
    path('<int:meeting_id>/comment-delete/<int:comment_id>/', views.comment_delete, name='comment-delete'),
    path('<int:meeting_id>/participate/', views.board_participate, name='participate'),
    path('<int:meeting_id>/participate-delete/', views.board_participate_delete, name='participate-delete'),
    path('<int:meeting_id>/gather-done/', views.board_gather_done, name='gather-done'),
    path('<int:meeting_id>/settle/', views.board_settle, name='settle'),
    path('<int:meeting_id>/meeting-complete/', views.board_meeting_complete, name='meeting-complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', views.index, name='index'), #루트 페이지 설정(고치자..)
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

boards/models.py
from django.db import models
from django.conf import settings
# Create your models here.


# 모임 상태 정보 테이블
class MeetingStatus(models.Model):
    status_number = models.IntegerField(primary_key=True, null=False)
    button_text = models.CharField(max_length=10)

    def __str__(self):
        return self.button_text


# 모임 경로 정보 테이블
class RouteInfo(models.Model):
    route_id = models.IntegerField(primary_key=True, null=False)
    value = models.CharField(max_length=10, null=False)

    def __str__(self):
        return self.value


# 모임 테이블
class Meeting(models.Model):
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='hosted_meetings')
    meeting_content = models.TextField(null=False, blank=False)
    status = models.ForeignKey(MeetingStatus, on_delete=models.CASCADE)
    route = models.ForeignKey(RouteInfo, on_delete=models.CASCADE, null=False, blank=False)
    total_amount = models.IntegerField(null=False, default=0)
    participant_count = models.IntegerField(default=1)
    created_at = models.DateTimeField(auto_now_add=True)


#모임 참여 테이블
class Participation(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, related_name='group')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


#댓글 테이블
class Comment(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.TextField(null=False, blank=False)


#모임 정산 테이블
class SettleUp(models.Model):
    meeting = models.ForeignKey(Meeting, on_delete=models.SET_NULL, null=True, related_name='settle')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    bank = models.CharField(max_length=10, default='')
    account_no = models.CharField(max_length=20, default='')
    amount = models.IntegerField(null=False)
    is_check = models.BooleanField(default=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True, null=False)

boards/forms.py
from django import forms
from .models import *

#게시글 생성 폼
class BoardForm(forms.ModelForm):
    class Meta:
        model = Meeting
        fields = ['meeting_content', 'route']


#댓글 생성 폼
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

boards/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

from .forms import BoardForm, CommentForm
from .models import *

# Create your views here.

#게시판 메인
def board_main(request):
    meeting_list = Meeting.objects.order_by('-created_at')
    meeting_status_list = MeetingStatus.objects.all()
    content = {
        'meeting_list': meeting_list,
        'meeting_status_list': meeting_status_list,
        'request': request,
    }
    return render(request, 'boards/board_main.html', content)


#게시판 글쓰기
def board_write(request):
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            meeting = form.save(commit=False)
            meeting.user_id = request.user
            meeting.status = MeetingStatus.objects.get(status_number=0)
            meeting.total_amount = 0
            meeting.participant_count = 1
            meeting.save()

            # Meeting 저장 후 Participation 인스턴스 생성
            participation = Participation(meeting=meeting, user=request.user)
            participation.save()

            return redirect('boards:main')
    else:
        form = BoardForm()
    routeInfo = RouteInfo.objects.all()
    return render(request, 'boards/board_write.html',
                  {'form': form, 'routeInfo': routeInfo})


#게시글 상세보기 & 댓글 쓰기
def board_detail(request, meeting_id):
    meeting = Meeting.objects.get(id=meeting_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.meeting = meeting
            comment.user = request.user
            comment.save()
            return redirect('boards:detail', meeting_id=meeting_id)
    else:
        form = CommentForm()
    participant = Participation.objects.filter(meeting=meeting_id)
    meeting_status_list = MeetingStatus.objects.all()
    comments = meeting.comments.all()

    from_page = request.GET.get('from')
    if from_page:
        request.session['from_page'] = from_page

    if request.session.get('from_page') == 'my_posts':
        back_url = '/accounts/user-write-board/'
    elif request.session.get('from_page') == 'main_posts':
        back_url = '/boards/'
    else:
        back_url = '/accounts/user-participate-board/'

    context = {
        'meeting': meeting,
        'meeting_status_list': meeting_status_list,
        'participant': participant,
        'request': request,
        'comments': comments,
        'back_url': back_url,
    }
    return render(request, 'boards/board_detail.html', context)


# 게시글 수정하기
def board_edit(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id) # 해당 모임 데이터 가져오기
    routeInfo = RouteInfo.objects.all() # 경로 정보 데이터 가져오기

    if request.method == 'POST': # POST로 접근 시(=폼 제출 시)
        route_id = request.POST.get('route')  # 사용자가 선택한 경로의 ID 가져오기
        route_instance = get_object_or_404(RouteInfo, route_id=route_id)  # 해당 ID에 맞는 RouteInfo 인스턴스 가져오기
        meeting.route = route_instance # 값 변경
        meeting.meeting_content = request.POST['meeting_content'] # 값 변경
        meeting.save()
        return redirect('boards:detail', meeting_id=meeting_id)
    else:
        form = BoardForm()
        return render(request, 'boards/board_edit.html',
                      {'meeting': meeting, 'routeInfo': routeInfo})


# 게시글 삭제하기
def board_delete(request, meeting_id):
    if request.method == 'POST':
        meeting = get_object_or_404(Meeting, id=meeting_id)
        meeting.delete()
        return redirect('boards:main')
    else:
        return render(request, 'boards/board_main.html')


# 댓글 삭제하기
def comment_delete(request, meeting_id, comment_id):
    if request.method == 'POST':
        comment = get_object_or_404(Comment, id=comment_id)
        comment.delete()
        return redirect('boards:detail', meeting_id=meeting_id)


# 모임 참여하기
def board_participate(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    if meeting.participant_count == 4:
        return redirect(request.META.get('HTTP_REFERER', 'default_route'))
    participation = Participation(meeting=meeting, user=request.user)
    participation.save()

    meeting.participant_count += 1
    meeting.save()
    return redirect(request.META.get('HTTP_REFERER', 'default_route'))


# 모임 참여취소하기
def board_participate_delete(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    Participation.objects.filter(meeting=meeting, user=request.user).delete()
    meeting.participant_count -= 1
    meeting.save()
    return redirect(request.META.get('HTTP_REFERER', 'default_route'))


# 모집 종료하기
def board_gather_done(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    meeting.status = MeetingStatus.objects.get(status_number=1)
    meeting.save()
    return redirect(request.META.get('HTTP_REFERER', 'default_route'))


# 정산하기
def board_settle(request, meeting_id):
    if request.method == 'POST':
        meeting = get_object_or_404(Meeting, id=meeting_id)
        total_amount = int(request.POST['total_amount'])
        if total_amount <= 0:
            return redirect('boards:detail', meeting_id=meeting.id)
        meeting.status = MeetingStatus.objects.get(status_number=2)
        meeting.total_amount = total_amount
        meeting.save()
        participation = Participation.objects.filter(meeting=meeting)
        for participant in participation:
            if meeting.user_id != participant.user:
                # print(meeting.user_id, participant.user, 'false!')
                amount = meeting.total_amount // meeting.participant_count
                SettleUp.objects.create(
                    meeting=meeting,
                    user=participant.user,
                    bank=meeting.user_id.bank,
                    account_no=meeting.user_id.account_no,
                    amount=amount
                )
        return redirect('boards:detail', meeting_id=meeting.id)


# 완료하기
def board_meeting_complete(request, meeting_id):
    meeting = get_object_or_404(Meeting, id=meeting_id)
    meeting.status = MeetingStatus.objects.get(status_number=3)
    meeting.save()
    return redirect('boards:detail', meeting_id=meeting.id)

templates/boards/board_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/board_detail.css' %}">
            <div class="top-logo">
                <div class="move-back">
                    <a href="{{ back_url }}">
                        <img src="{% static 'image/back.png' %}" alt="">
                    </a>
                </div>
                게시판
            </div>

            <div class="post"> <!--⭐⭐-->
                <div class="post-hd"> <!--프로필, 닉네임, 모집종료 아이콘, 경로-->
                    <div class="user-profile"> <!--프로필 사진-->
                        <img src="{% static 'image/profile-post-detail.png' %}" alt="">
                    </div>

                    <div class="user-nickname"> <!-- ⭐⭐닉네임 -->
                        {{ meeting.user_id.nickname }}
                    </div>

                    {% if meeting.status.status_number > 0 %}
                        <div class="end-icon"> <!--모임 종료 아이콘 -->
                            <img src="{% static 'image/end-icon.png' %}" alt="">
                        </div>
                    {% endif %}

                    <div class="route"> <!--⭐⭐ 경로 -->
                        {{ meeting.route }}
                    </div>
                </div>

                <div class="post-content"> <!--⭐⭐게시글 내용-->
                    {{ meeting.meeting_content|linebreaksbr }}
                </div>

                <div class="post-ft"> <!--인원수, 참여하기(or 종료하기) 버튼-->
                    <div class="people-count"> <!--인원수-->
                        <img src="{% static 'image/people.png' %}" alt=""> <!--사람들 아이콘-->
                        <span>{{ meeting.participant_count }}명 / 4명</span> <!--⭐⭐ 인원수 글자 -->
                    </div>

                    <div class="post-btn"> <!--참여하기(or 종료하기) 버튼-->
                        {% load custom_tags %}
                        {% button_text meeting.id as Participant_list%}
                        {% if meeting.user_id == request.user %}
                            {% if meeting.status.status_number == 0 %}
                                <a href="{% url 'boards:gather-done' meeting.id %}">
                                    <div class="meeting-btns">모집종료</div>
                                </a>
                            {% elif meeting.status.status_number == 1 %} <!--정산하기-->
                                <button type="button" class="state-btn">{{ meeting.status.button_text }}</button>
                            {% elif meeting.status.status_number == 2 %}
                                <a href="{% url 'boards:meeting-complete' meeting.id %}"> <!--완료하기-->
                                    <div class="meeting-btns">{{ meeting.status.button_text }}</div>
                                </a>
                            {% else %}
                                <div class="meeting-btns-complete">{{ meeting.status.button_text }}</div>
                            {% endif %}
                        {% else %}
                            {% if meeting.status.status_number == 0 %}
                                {% if Participant_list %}
                                    <a href="{% url 'boards:participate-delete' meeting.id %}">
                                        <div class="meeting-btns">참여취소</div>
                                    </a>
                                {% else %}
                                    {% if meeting.participant_count == 4 %}
                                        <div></div>
                                    {% else %}
                                        <a href="{% url 'boards:participate' meeting.id %}">
                                            <div class="meeting-btns">참여하기</div>
                                        </a>
                                    {% endif %}
                                {% endif %}
                            {% elif meeting.status.status_number < 3 %}
                                <div class="meeting-btns">모임진행</div>
                            {% else %}
                                <div class="meeting-btns-complete">{{ meeting.status.button_text }}</div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>

                <div class="people-detail">
                    <div class="title-text"> <!--아이콘, 참여한 사람 텍스트 부분-->
                        <img src="{% static 'image/people.png' %}" alt="">
                        참여한 사람
                    </div>

                    <div class="group-users"> <!--⭐⭐ 택시 모임에 참여한 인원 부분-->
                        {% for member in participant %}
                            <span class="members">{{ member.user.nickname }}</span>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="comment"> <!--댓글 작성 부분-->
                <div class="comment-text">
                    <div class="comment-img"><img src="{% static 'image/comment.png' %}" alt=""></div>
                    <div class="comment-title">댓글 작성</div>
                </div>

                <form action="/boards/{{ meeting.id }}/" method="post" id="comment-form"> <!--⭐⭐댓글 등록 textarea-->
                    {% csrf_token %}
                    <div>
                        <textarea name="content" id="comment-area" placeholder="댓글 작성" maxlength="99" spellcheck="false"></textarea>
                        <div class="submit-btn">
                            <button type="submit">등록</button>
                        </div>
                    </div>
                </form>

                <div id="text-count">0 / 100</div>
            </div>

            <div class="line"></div> <!--구분선-->

            {% for comment in comments %}
            <div class="user-comment"> <!--⭐⭐ 댓글들-->
                <div class="comment-hd"> <!--댓글 윗부분 영역-->
                    <div><img src="{% static 'image/profile-post-detail.png' %}" alt=""></div> <!--프로필 사진-->
                    <div class="comment-nickname">{{ comment.user.nickname }}</div> <!--닉네임-->
                    {% if comment.user == request.user %}
                        <form action="{% url 'boards:comment-delete' meeting.id comment.id %}" method="post" class="comment-delete">
                            {% csrf_token %}
                            <button type="submit" class="comment-delete-btn">삭제</button>
                        </form>
                    {% else %}
                        <div class="comment-delete"></div>
                    {% endif %}
                </div>

                <div class="comment-content"> <!--댓글 내용-->
                    {{ comment.content|linebreaksbr }}
                </div>
            </div>
            <div class="comment-line"></div> <!--댓글 구분선-->
            {% endfor %}

            {% if meeting.user_id == request.user %}
                <button type="button" id="dots-btn"> <!--⭐... 버튼-->
                    <img src="{% static 'image/dots.png' %}" alt="">
                </button>
            {% endif %}

            <div class="btns">
                <a href="{% url 'boards:edit' meeting.id %}">
                    <button type="button" class="edit-btn">수정하기</button> <!--⭐⭐수정하기 버튼-->
                </a>

                <button type="button" class="delete-btn">삭제하기</button> <!--⭐⭐삭제하기 버튼-->
            </div>

            <div id="modal"> <!--모달창-->
                <div class="modal-contents">
                    <button type="button" class="btn-close"></button>
                    <div class="modal-title">글을 삭제하시겠습니까?</div>
                    <a href="#"><div class="closePopup">아니오</div></a>
                    <form class="yesBtn" method="post" action="{% url 'boards:delete' meeting.id %}">
                        {% csrf_token %}
                        <button type="submit" class="delete_post">네</button> <!--⭐⭐여기 글 삭제 버튼-->
                    </form>
                </div>
            </div>

            <div class="settle-modal"> <!--정산하기 모달창-->
                <div class="settle-modal-title">정산하기 <span class="error"></span></div>
                <form action="{% url 'boards:settle' meeting.id %}" method="post" class="settle-form"> <!--⭐⭐ 정산 폼-->
                    {% csrf_token %}
                    <input type="number" id="user_id" name="total_amount" placeholder="택시가격을 입력해주세요. ex) 8000" value="" required>

                    <div class="settle-modal-btns"> <!--확인, 취소 버튼-->
                        <button type="button" class="cancel-btn">취소</button>
                        <button type="submit" class="yes-btn">확인</button>
                    </div>
                </form>
            </div>
        {% include 'menuBar_boards.html' %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/board_detail.js' %}"></script>
{% endblock %}

templates/boards/board_main.html
{% extends 'base.html' %}
{% block content%}
    {% load static%}
    <link rel="stylesheet" href="{% static 'css/board_main.css' %}">
            <div class="banner"> <!--상단 배너 부분-->
                <div class="banner-img"> <!--상단 배너 이미지(택시)-->
                    <img src="{% static 'image/taxi.png' %}" alt="">
                </div>

                <div class="taxi-info"> <!--택시 요금 정보 부분-->
                    <div class="info-text"> <!-- 택시 요금 정보 글자들 -->
                        <div class="info-title">
                            택시 요금 정보
                        </div>
                        <div class="refresh-btn">
                            <button type="button" id="api-btn">
                                <img src="{% static 'image/refresh.png' %}" alt=""> <!--⭐⭐요금 정보 불러오기 버튼-->
                            </button>
                        </div>
                        <div class="warn-text">※ 상황에 따라 요금이 다를 수 있습니다.</div>
                    </div>

                    <div class="taxi-fee"> <!--택시 가격들-->
                        <div class="fee-box"> <!--왕십리역-->
                            <div class="fee-title">왕십리역 ↔ 학교</div>
                            <div class="fee">0원</div> <!--⭐⭐여기 가격 ajax?-->
                        </div>

                        <div class="fee-box"> <!--한양대역-->
                            <div class="fee-title">한양대역 ↔ 학교</div>
                            <div class="fee">0원</div> <!--⭐⭐여기 가격 ajax?-->
                        </div>

                        <div class="fee-box"> <!--마장역-->
                            <div class="fee-title">마장역 ↔ 학교</div>
                            <div class="fee">0원</div> <!--⭐⭐여기 가격 ajax?-->
                        </div>
                    </div>
                </div>
            </div><!--상단 배너 부분 끝-->

            {% if not meeting_list %}
                <div class="no-meeting-img">
                    <img src="{% static 'image/not-exists.png' %}" alt="">
                </div>
                <div class="no-meeting-notice">모임이 없습니다.</div>
                <div class="no-meeting-notice-long">모임을 추가해 보세요!</div>
            {% endif %}

            <!--⭐⭐반복문- 유저들이 작성한 글-->
            {% for meeting in meeting_list %}
                {% load custom_tags %}
                {% button_text meeting.id as Participant_list%}
            <div class="post">
                <div class="post-hd"> <!--프로필, 닉네임, 모집종료 아이콘, 경로-->
                    <div class="user-profile"> <!--프로필 사진-->
                        <img src="{% static 'image/profile.png' %}" alt="">
                    </div>

                    <div class="user-nickname"> <!-- 닉네임 -->
                        {{ meeting.user_id.nickname }}
                    </div>

                    {% if meeting.status.status_number > 0 %}
                        <div class="end-icon"> <!--모임 종료 아이콘 -->
                            <img src="{% static 'image/end-icon.png' %}" alt="">
                        </div>
                    {% endif %}

                    <div class="route"> <!-- 경로 -->
                        {{ meeting.route }}
                    </div>
                </div>

                <a href="{% url 'boards:detail' meeting.id %}?from=main_posts" class="detail_link">
                    <div class="post-content"> <!--게시글 내용-->
                        {{ meeting.meeting_content|linebreaksbr }}
                    </div>
                </a>

                <div class="post-ft"> <!--인원수, 참여하기(or 종료하기) 버튼-->
                    <div class="people-count"> <!--인원수-->
                        <img src="{% static 'image/people.png' %}" alt=""> <!--사람들 아이콘-->
                        <span>{{ meeting.participant_count }}명 / 4명</span> <!--⭐⭐ 인원수 글자 -->
                    </div>
                    <div class="post-btn">
                        {% if meeting.user_id == request.user %}
                            <div class="{% if meeting.status.status_number >= 3 %}meeting-btns-complete{% else %}meeting-btns{% endif %}">
                                {% if meeting.status.status_number == 0 %}
                                    마감하기
                                {% else %}
                                    {{ meeting.status.button_text }}
                                {% endif %}
                            </div>
                        {% else %}
                            {% if meeting.status.status_number == 0 %}
                                {% if Participant_list %}
                                    <div class="meeting-btns2">참여중</div>
                                {% else %}
                                    {% if meeting.participant_count == 4 %}
                                        <div class="meeting-btns">참여불가</div>
                                    {% else %}
                                        <div class="meeting-btns">참여가능</div>
                                    {% endif %}
                                {% endif %}
                            {% elif meeting.status.status_number < 3 %}
                                <div class="meeting-btns">모임진행</div>
                            {% else %}
                                <div class="meeting-btns-complete">{{ meeting.status.button_text }}</div>
                            {% endif %}
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="line"></div> <!--구분선-->
            {% endfor %}

            <a href="{% url 'boards:write' %}"> <!--⭐⭐여기 링크 연결-->
                <button type="button" class="write-btn"> <!--글 작성 버튼-->
                    &#43;
                </button>
            </a>

            <a href="#">
                <button type="button" class="up-btn"> <!--멘 위로 올라가기 버튼 #으로 이동-->
                    <img src="{% static 'image/arrow.png' %}" alt="">
                </button>
            </a>

        {% include 'menuBar_boards.html' %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/board_main.js' %}"></script>
{% endblock %}

templates/boards/board_write.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/board_write.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
            <div class="top-logo">
                <div class="move-back">
                    <a href="{% url 'boards:main' %}">
                        <img src="{% static 'image/back.png' %}" alt="">
                    </a>
                </div>
                작성
            </div>

            <form method="post" action="{% url 'boards:write' %}" class="check-box"> <!--⭐⭐여기 폼-->
                {% csrf_token %}
                {% for route in routeInfo %}
                <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" name="route" id="inlineRadio{{ forloop.counter }}" value="{{ route.route_id }}" required>
                    <label class="form-check-label" for="inlineRadio{{ forloop.counter }}">{{ route.value }}</label>
                </div>
                {% endfor %}

                <button type="submit" id="submit-btn">등록</button> <!--⭐등록버튼-->

                <div class="line"></div>

                <textarea name="meeting_content" id="write-text" placeholder="글을 작성해주세요." maxlength="149" spellcheck="false" required></textarea>

                <div id="text-count">0 / 150</div>
            </form>
        {% include 'menuBar_boards.html' %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="{% static 'js/board_write.js' %}"></script>
{% endblock %}

templates/boards/user_participate_board.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/user_participate_board.css' %}">
            <div class="top-logo">
                <div class="move-back">
                    <a href="{% url 'accounts:user_page' %}">
                        <img src="{% static 'image/back.png' %}" alt="">
                    </a>
                </div>
                참여한 모임
            </div>

            {% if not meeting_list %}
                <div class="not-exists-img">
                    <img src="{% static 'image/not-exists.png' %}" alt="">
                </div>
                <div class="no-notice">참여한 모임이 없습니다.</div>
            {% endif %}

            <!--⭐⭐반복문- 유저들이 작성한 글-->
            {% for meeting in meeting_list %}
                {% load custom_tags %}
                {% button_text meeting.id as Participant_list%}
            <div class="post">
                <div class="post-hd"> <!--프로필, 닉네임, 모집종료 아이콘, 경로-->
                    <div class="user-profile"> <!--프로필 사진-->
                        <img src="{% static 'image/profile.png' %}" alt="">
                    </div>

                    <div class="user-nickname"> <!-- 닉네임 -->
                        {{ meeting.user_id.nickname }}
                    </div>

                    {% if meeting.status.status_number > 0 %}
                        <div class="end-icon"> <!--모임 종료 아이콘 -->
                            <img src="{% static 'image/end-icon.png' %}" alt="">
                        </div>
                    {% endif %}

                    <div class="route"> <!-- 경로 -->
                        {{ meeting.route }}
                    </div>
                </div>

                <a href="{% url 'boards:detail' meeting.id %}?from=participate_posts" class="detail_link">
                    <div class="post-content"> <!--게시글 내용-->
                        {{ meeting.meeting_content }}
                    </div>
                </a>

                <div class="post-ft"> <!--인원수, 참여하기(or 종료하기) 버튼-->
                    <div class="people-count"> <!--인원수-->
                        <img src="{% static 'image/people.png' %}" alt=""> <!--사람들 아이콘-->
                        <span>{{ meeting.participant_count }}명 / 4명</span> <!--⭐⭐ 인원수 글자 -->
                    </div>
                    <div class="post-btn">
                        {% if meeting.status.status_number == 0 %}
                            <div class="meeting-btns2">참여중</div>
                        {% elif meeting.status.status_number < 3 %}
                            <div class="meeting-btns">모임진행</div>
                        {% else %}
                            <div class="meeting-btns-complete">{{ meeting.status.button_text }}</div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="line"></div> <!--구분선-->
            {% endfor %}
        {% include 'menuBar_mypage.html' %}
{% endblock %}