accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    path('send-email/', views.send_email, name='send_email'),
    path('send-email/done/', views.send_email_done, name='send_email_done'),
    path('user-delete/', views.user_delete, name='user_delete'),
    path('signUp/', views.signUp, name='signUp'), #회원가입
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'), #로그인
    path('signUp/id-check/', views.check_id, name='id-check'), #아이디 중복 검사
    path('signUpComplete/', views.signUpComplete, name='signUpComplete'), #회원가입 완료
    path('user-page/', views.user_page, name='user_page'), #마이페이지
    path('logout/', views.logout_view, name='logout'),
    path('<int:settle_id>/settle-is-check/', views.settle_check, name='settle-check'),
    path('account-change/', views.account_change, name='account_change'),
    path('nickname-change/', views.nickname_change, name='nickname_change'),
    path('user-write-board/', views.user_write_board, name='user_write_board'),
    path('user-participate-board/', views.user_participate_board, name='user_participate_board'),
]

boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    path('', views.board_main, name='main'),
    path('write/', views.board_write, name='write'),
    path('<int:meeting_id>/', views.board_detail, name='detail'),
    path('<int:meeting_id>/edit/', views.board_edit, name='edit'),
    path('<int:meeting_id>/delete/', views.board_delete, name='delete'),
    path('<int:meeting_id>/comment-delete/<int:comment_id>/', views.comment_delete, name='comment-delete'),
    path('<int:meeting_id>/participate/', views.board_participate, name='participate'),
    path('<int:meeting_id>/participate-delete/', views.board_participate_delete, name='participate-delete'),
    path('<int:meeting_id>/gather-done/', views.board_gather_done, name='gather-done'),
    path('<int:meeting_id>/settle/', views.board_settle, name='settle'),
    path('<int:meeting_id>/meeting-complete/', views.board_meeting_complete, name='meeting-complete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts import views

urlpatterns = [
    path('', views.index, name='index'), #루트 페이지 설정(고치자..)
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>함께나리</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container-content"> <!--전체 영역-->
        <div class="contents"> <!--전체 컨텐츠 영역-->
            {% block content %}

            {% endblock %}
        </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/menuBar_boards.html
        {% load static %}
        <div class="menu"> <!--메뉴바(footer) 영역-->
            <div class="menu-icons">
                <div>
                    <a href="{% url 'boards:main' %}"><img src="{% static 'image/write-yellow.png' %}" alt="" class="write"></a>
                </div>
                <div>
                    <a href="{% url 'index' %}"><img src="{% static 'image/home.png' %}" alt="" class="home"></a>
                </div>
                <div>
                    <a href="{% url 'accounts:user_page' %}"><img src="{% static 'image/user-info.png' %}" alt="" class="user"></a>
                </div>
            </div>
        </div>

templates/menuBar_home.html
        {% load static %}
        <div class="menu"> <!--메뉴바(footer) 영역-->
            <div class="menu-icons">
                <div>
                    <a href="{% url 'boards:main' %}"><img src="{% static 'image/write.png' %}" alt="" class="write"></a>
                </div>
                <div>
                    <a href="{% url 'index' %}"><img src="{% static 'image/home-yellow.png' %}" alt="" class="home"></a>
                </div>
                <div>
                    <a href="{% url 'accounts:user_page' %}"><img src="{% static 'image/user-info.png' %}" alt="" class="user"></a>
                </div>
            </div>
        </div>

templates/menuBar_mypage.html
        {% load static %}
        <div class="menu"> <!--메뉴바(footer) 영역-->
            <div class="menu-icons">
                <div>
                    <a href="{% url 'boards:main' %}"><img src="{% static 'image/write.png' %}" alt="" class="write"></a>
                </div>
                <div>
                    <a href="{% url 'index' %}"><img src="{% static 'image/home.png' %}" alt="" class="home"></a>
                </div>
                <div>
                    <a href="{% url 'accounts:user_page' %}"><img src="{% static 'image/user-info-yellow.png' %}" alt="" class="user"></a>
                </div>
            </div>
        </div>